services:

  api:
    build:
      context: ./transaction-validator
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - localstack

  consumer:
    build:
      context: ./paymentprocessor
      dockerfile: dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - localstack

  db:
    image: postgres:17
    container_name: transaction-validator
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: transaction-validator-db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_consumer:
    image: postgres:17
    container_name: paymentprocessor
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: payment-processor-db
    ports:
      - "5433:5432"
    volumes:
      - paymentprocessor_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # Porta unificada para todos os serviços AWS
      - "4571:4571"   # Porta para a UI (opcional, depende da versão)
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock  # necessário para algumas funções do LocalStack
volumes:
  postgres_data:
  localstack_data:
  paymentprocessor_data: